# Generated by Django 4.2 on 2023-04-27 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='createdAt',
            field=models.DateField(default=datetime.datetime(2023, 4, 27, 14, 9, 55, 207082)),
        ),
    ]
