# Generated by Django 4.2 on 2023-04-27 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='createdAt',
            field=models.DateField(default=datetime.datetime(2023, 4, 27, 20, 10, 55, 776308, tzinfo=datetime.timezone.utc)),
        ),
    ]
