# Generated by Django 4.2 on 2023-04-27 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='createdAt',
            field=models.DateField(default=datetime.date(2023, 4, 27)),
        ),
    ]
