# Generated by Django 4.2 on 2023-04-27 20:46

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_book_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='book',
            name='details',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='details'),
        ),
    ]
