# Generated by Django 4.2 on 2023-05-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('r', 'Ready to Delivery'), ('d', 'On Route'), ('dch', 'Delivered Charge'), ('c', 'Completed')], default='r', max_length=4),
        ),
    ]
