# Generated by Django 4.2 on 2023-05-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='revenue',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
